[versions]

kotlin = "2.4.20"
kotlinx_serialization = "1.11.0"
kotlinx_io = "0.9.1"
android_plugin = "9.4.1"
maven_publish = "0.37.0"

[libraries]

kotlinx-serialization    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx_serialization" }
kotlinx-io               = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx_io" }

[plugins]

kotlin-multiplatform    = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android          = { id = "com.android.kotlin.multiplatform.library", version.ref = "android_plugin" }
kotlin-serialization    = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven_publish           = { id = "com.vanniktech.maven.publish", version.ref = "maven_publish" }