[versions]

kotlin = "2.4.10"
kotlin_serialization = "1.11.0"
android_plugin = "9.1.1"
maven_publish = "0.37.0"

[libraries]

kotlin-serialization    = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin_serialization" }

[plugins]

kotlin-multiplatform    = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android          = { id = "com.android.kotlin.multiplatform.library", version.ref = "android_plugin" }
kotlin-serialization    = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven_publish           = { id = "com.vanniktech.maven.publish", version.ref = "maven_publish" }